# --------------------------------
# GeyserMulti Configuration File
# --------------------------------

# The IP address that will listen for connections
address: 0.0.0.0

# The IP address remote clients use to connect, can be set to 'auto' to fetch from the web
remote-address: auto

# The port that will listen for connections
port: 19132

# If debug messages should be sent through console
debug-mode: false

# Maximum amount of players that can connect
max-players: 100

# MOTD to display
motd: "GeyserMulti Proxy"

# Config for the geyser listener
geyser:
  # The port that will listen for connections
  port: 19133

  # If debug messages should be sent through console, has to be enabled in both places to work
  debug-mode: false

# A global list of servers sent to all clients
servers:
  - address: "play.cubecraft.net"
  - address: "127.0.0.1"
    port: 25565

custom-servers:
  # Should custom servers be enabled for users
  enabled: false

  # Max amount of custom servers per user
  max: 10

  # Storage engine for custom servers
  # Can be json, sqlite
  storage-type: json
