name: Build Pull Request

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.idea/copyright/*.xml' 
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'bind9/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: temurin

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build GeyserConnect
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: GeyserConnect
          path: build/libs/GeyserConnect.jar
